### ISSUE TITLE
Allow inserting ranges

### ISSUE THREAD

**Issue by UmanShahzad** [maxmind/mmdbwriter#23]
The Perl writer allows inserting IP ranges as well as IP networks. The Go writer only supports IP networks currently, so users requiring range insertions must convert ranges to networks manually first.

**Comment by UmanShahzad** [comment]
I can possibly contribute this feature.

**Comment by UmanShahzad** [comment]
@oschwald would you be okay if I had to include a new library for achieving this?

**Comment by oschwald** [comment]
That seems fine. Did you have a particular library in mind? `github.com/inetaf/netaddr` might be a good candidate, although they do make breaking changes from time to time yet. I'd probably prefer if it was not part of the external API so that we could easily replace the underlying implementation if necessary.

**Comment by UmanShahzad** [comment]
`netaddr` is definitely one, but another one is one that I wrote over at https://github.com/ipinfo/cli/tree/master/lib - it's kind of a collection of many things but I can break out the IPv4/6 range/subnet-related code into a separate package. The particular functions I'd use are:

- [ToIP6Subnets](https://github.com/ipinfo/cli/blob/c61acaa0959afd97c0b930a11124623ac2f46a00/lib/ip6_range.go#L77-L96) to get all subnets within a range. Can also create a callback-based function so that we don't have to store all subnets in memory at once before writing them out to the tree.
- Functions to convert `net.IP` into `IP6` so we can use the above function.
- Functions to convert the return type `IP6Subnet` into `net.IPNet` so we can use it in `tree.Insert`.

I'm fine with whatever you decide; can use either lib. Either way, a library will be needed, since we need to work on 128-bit numbers for calculating ipv6 subnets from ranges efficiently. It's not a lot of code to implement the needed 128-bit adds + bitwise-and/or, but guessing you don't want that in the codebase.

**Comment by oschwald** [comment]
I'd prefer `netaddr` as we are already using it internally. I think you could just use the [`IPRange` type](https://pkg.go.dev/inet.af/netaddr#IPRange) and the [`Prefixes` method](https://pkg.go.dev/inet.af/netaddr#IPRange.Prefixes) to get the networks.

**Comment by UmanShahzad** [comment]
Alright, no problem. Will probably make a PR tomorrow.

**Comment by UmanShahzad** [comment]
Made https://github.com/maxmind/mmdbwriter/pull/25
