### ISSUE TITLE
about city data

### ISSUE THREAD

**Issue by zuozhehao** [maxmind/mmdbwriter#73]
Is there a specific document on the data structure and examples related to city

**Comment by horgh** [comment]
We currently don't have documentation about the structure of the MMDBs. Typically it is easiest to use one of our [API clients](https://dev.maxmind.com/geoip/docs/databases/#client-apis).

However, one way you can look at the structure is by using https://github.com/maxmind/mmdbinspect or mmdblookup from https://github.com/maxmind/libmaxminddb for an IP/network. Note that not every IP/network has every value populated though.
