### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by shenqisimao** [maxmind/mmdbwriter#9]
# github.com/maxmind/mmdbwriter/mmdbtype
../go/src/github.com/maxmind/mmdbwriter/mmdbtype/types.go:290:23: syntax error: unexpected b00100000, expecting comma or )
../go/src/github.com/maxmind/mmdbwriter/mmdbtype/types.go:300:23: syntax error: unexpected b00101000, expecting comma or )
../go/src/github.com/maxmind/mmdbwriter/mmdbtype/types.go:314:23: syntax error: unexpected b00110000, expecting comma or )
../go/src/github.com/maxmind/mmdbwriter/mmdbtype/types.go:331:23: syntax error: unexpected b00111000, expecting comma or )

**Comment by oschwald** [comment]
You'll need Go 1.13 or greater.
