### ISSUE TITLE
Create MMDB USE CSV GeoLite2-Country

### ISSUE THREAD

**Issue by IgV52** [maxmind/mmdbwriter#91]
Hello, I create mmdb but she != GeoLite2-Country.mmdb, what settings do you use to prevent subnets from merging?

**Comment by oschwald** [comment]
I am not sure I fully understand your comment, but there isn't currently a way to prevent subnets from merging. The `GeoLite2-Country.mmdb` database is created with this writer so if subnets are being merged that are not merged there, there must be data differences.
