### ISSUE TITLE
Is the MMDB writer thread safe?

### ISSUE THREAD

**Issue by mandar-01** [maxmind/mmdbwriter#92]
I am planning to concurrently insert data into MMDB using go routines. Each routine will read data from a source and insert it to the writer object. Once all ingestion is done, I am planning to save the MMDB file. Here is how I have defined the writer:

`
writer, err := mmdbwriter.New(
		mmdbwriter.Options{
			IncludeReservedNetworks: true,
			RecordSize: 32,
		},
	)
`

Can I invoke `writer.InsertFunc()` from multiple go routines?

**Comment by oschwald** [comment]
No, it is not thread safe. You would need to guard it with a mutex.
