### ISSUE TITLE
Issues with writing 2001::/32 to MMDB and querying

### ISSUE THREAD

**Issue by ac-hj** [maxmind/mmdbwriter#94]
Hi, this is a follow-up to the [issue in Python reader library](https://github.com/maxmind/MaxMind-DB-Reader-python/issues/171). I'm currently using this Go library to write `2001::/32` to an MMDB file, but I'm unable to correctly query IP's in that network. 

Here's the code I'm using to write to the file. Note that I'm not storing any metadata for each network; ultimately, I'm hoping to just check whether the given IP exists in any of the networks stored in the MMDB file. `bogon_cidr.csv` is a file with bogons/reserved networks with one column called `network`, including `2001::/32`.
```
func main() {
	writer, err := mmdbwriter.New(
		mmdbwriter.Options{
			DatabaseType: "private-and-bogon-ip-prefixes",
            IPVersion: 6,
            IncludeReservedNetworks: true, // By default, reserved networks aren't allowed. 
            DisableIPv4Aliasing: true, // Suppressing aliasing issue (e.g., with 2001::/32)
		},
	)
	if err != nil {
		log.Fatal(err)
	}

    for _, file := range []string{"bogon_cidr.csv"} {
		fh, err := os.Open(file)
		if err != nil {
			log.Fatal(err)
		}

		r := csv.NewReader(fh)

		// first line
		r.Read()

		for {
			row, err := r.Read()
			if err == io.EOF {
				break
			}
			if err != nil {
				log.Fatal(err)
			}
            
			if len(row) != 1 {
				log.Fatalf("unexpected CSV rows: %v", row)
			}

			_, network, err := net.ParseCIDR(row[0])
			if err != nil {
				log.Fatal(err)
			}

			record := mmdbtype.Map{}

            
			err = writer.Insert(network, record)
			if err != nil {
				log.Fatalf("unexpected error for %v with %v", err, network)
			}
		}
	}

	fh, err := os.Create("bogon_cidr.mmdb")
	if err != nil {
		log.Fatal(err)
	}

	_, err = writer.WriteTo(fh)
	if err != nil {
		log.Fatal(err)
	}
}
```

What's interesting is that querying for IP's like `2001:0000:0000:0000:0000::` and `2001::` returns a valid result (i.e., `{}`), but querying for `2001:0034:abcd:1234:5678::` returns nothing.

**Comment by oschwald** [comment]
` 2001:0034:abcd:1234:5678::` isn't in `2001::/32`. Did you intend to insert `2001::/16` or some other network?

It would help if the example included the actual data being inserted so that I could make sure we are referring to the same thing.
