### ISSUE TITLE
The writer module is not working properly

### ISSUE THREAD

**Issue by Ketan-Desai** [maxmind/mmdbwriter#99]
Hi,

Please refer to the attached zip containing following files...

1. go source to read list of filenames in source.txt file and produce IP.db file (i.e. mmdb file)
2. TOR.txt file containing list of IP addresses

TOR.txt file header = network,organization,address,country,lat,long,accuracy,type

After producing the IP.db file, I am verifying via mmdbinspect and it's output do not match with the source

For Example...

The first line = 171.25.193.25/1,"TOR","","Sweden",59.3247,18.056,500,13

Network: 171.25.193.25/1
org = TOR
address = <blank>
country = Sweden
lat = 59.3247
long = 18.056,500
accuracy = 500
type = 13

Where as mmdbinspect output shows...

{
        "Database": "IP.db",
        "Records": [
            {
                "Network": "171.25.193.25/1",
                "Record": {
                    "accuracy": "1000",
                    "address": "Las Vegas, Nevada, 89119",
                    "country": "United States",
                    "lat": "36.102",
                    "long": "-115.1447",
                    "org": "TOR",
                    "type": 13
                }
            }
        ],
        "Lookup": "171.25.193.25"
    }

[make-ip.zip](https://github.com/user-attachments/files/17243260/make-ip.zip)

**Comment by oschwald** [comment]
I have not looked at your code or your input data, but based on `171.25.193.25/1`, I assume you are using invalid CIDR notation throughout.  `171.25.193.25/1` is equivalent to `128.0.0.0/1` in canonical form and covers half of the IPv4 space. I assume you intended to use `171.25.193.25/32`.

**Comment by Ketan-Desai** [comment]
ohh, very sorry sir.

It should be /32 :)
